trigger:
  branches:
    include:
      - master
      
pr:
  branches:
    exclude:
    - '*'

schedules:
  - cron: "0 0 * * *"
    displayName: Every day midnight build
    branches:
      include:
        - master
    always: true

resources:
  repositories:
    - repository: azureCommonTemplates
      type: github
      name: KontextWork/azure-common-templates
      ref: master
      endpoint: KontextWork

stages:
  - stage: build_and_push
    displayName: Build and Push
    jobs:
    - job: 
      displayName: Build and Push
      pool:
        vmImage: "ubuntu-latest"
      steps:
        - task: Docker@2
          displayName: Login to docker hub registry
          inputs:
            command: login
            containerRegistry: kw_docker_hub

        - bash: |
            sudo apt install -y m4 make
            make debian
          displayName: Build images

        - bash:
            make push
          displayName: Push images to registry

