trigger:
  branches:
    include:
      - master

variables:
  - group: kw-maven-nexus-author
  - group: kw-maven-nexus-reader
  - name: GRADLE_USER_HOME
    value: $(Pipeline.Workspace)/.gradle

resources:
  repositories:
    - repository: azureCommonTemplates
      type: github
      name: KontextWork/azure-common-templates
      ref: master
      endpoint: KontextWork

stages:
  - stage: build_and_push
    displayName: Build and Push
    jobs:
    - job: 
      displayName: Build and Push
      pool:
        vmImage: "ubuntu-latest"
      steps:
        - bash: make build
          displayName: Build images
	- bash: make push
	  displayName: Push images to registry

