name: build_php

on:
  push:
  schedule:
    - cron: '30 0 * * */2'

env:
  IMAGE_FQDN: ghcr.io/eugenmayer/azure

jobs:
  docker:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php: ['7.4', '8.1', '8.2', '8.3']
        debian: ['bullseye', 'bookworm']
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
        # https://github.com/docker/build-push-action/issues/761#issuecomment-1575006515
        with:
          driver-opts: |
            image=moby/buildkit:v0.10.6
      - name: Login to GHCR
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ github.token }}
      # push only on main
      - name: Build
        uses: docker/build-push-action@v3
        with:
          context: debian/php
          platforms: linux/amd64
          push: true
          tags: |
            ${{ env.IMAGE_FQDN }}:php-${{ matrix.php }}-${{ matrix.debian }}
          build-args: |
            PHP_VERSION=${{ matrix.php }}
            FROM_IMAGE=debian:${{ matrix.debian }}
