name: build_node

on:
  push:
  schedule:
    - cron: '30 23 * * */2'

env:
  IMAGE_FQDN: ghcr.io/eugenmayer/azure

jobs:
  docker:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 2
      matrix:
        node: ['10', '16', '18', '20', '22', 24]
        debian: ['buster', 'bullseye', 'bookworm']
        exclude:
          - node: 10
            debian: bullseye
          - node: 10
            debian: bookworm
          - node: 16
            debian: buster
          - node: 18
            debian: buster
          - node: 20
            debian: buster
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
        # https://github.com/docker/build-push-action/issues/761#issuecomment-1575006515
        with:
          driver-opts: |
            image=moby/buildkit:v0.10.6
      - name: Login to GHCR
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ github.token }}
      # push only on main
      - name: Build
        uses: docker/build-push-action@v3
        with:
          context: debian/
          platforms: linux/amd64
          push: true
          tags: |
            ${{ env.IMAGE_FQDN }}:node-${{ matrix.node }}-${{ matrix.debian }}
          build-args: |
            FROM_IMAGE=node:${{ matrix.node }}-${{ matrix.debian }}
